package empleadoscrud;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 
 * 
 */


public class EmpleadosCRUD extends javax.swing.JFrame {
    
    ConexionMYSQL con = new ConexionMYSQL();
    Connection cx = (Connection) con.conectar();
    
    public EmpleadosCRUD() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiarCampos();
        mostrarDatos("");
        txtID.setEnabled(false);
        txtIDEmp.requestFocus();
        btnActualizar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAgregar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        popEliminar = new javax.swing.JMenuItem();
        pnlPrincipal = new javax.swing.JPanel();
        pnlUsuarios = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtIDEmp = new javax.swing.JTextField();
        txtNomEmp = new javax.swing.JTextField();
        txtSexEmp = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        txtFecIngreso = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtComision = new javax.swing.JTextField();
        txtCargoE = new javax.swing.JTextField();
        txtJefeID = new javax.swing.JTextField();
        txtcodDepto = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        tblPanel = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();

        popEliminar.setText("jMenuItem1");
        popEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popEliminarActionPerformed(evt);
            }
        });
        popMenu.add(popEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(102, 102, 102));

        pnlUsuarios.setBackground(new java.awt.Color(102, 102, 102));
        pnlUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseClicked(evt);
            }
        });

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtID.setEnabled(false);

        txtIDEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtIDEmp.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtIDEmp.setForeground(new java.awt.Color(0, 0, 0));
        txtIDEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Emp"));
        txtIDEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDEmpActionPerformed(evt);
            }
        });

        txtNomEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtNomEmp.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtNomEmp.setForeground(new java.awt.Color(0, 0, 0));
        txtNomEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("NomEmp"));
        txtNomEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEmpActionPerformed(evt);
            }
        });

        txtSexEmp.setBackground(new java.awt.Color(255, 255, 255));
        txtSexEmp.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtSexEmp.setForeground(new java.awt.Color(0, 0, 0));
        txtSexEmp.setBorder(javax.swing.BorderFactory.createTitledBorder("Sex Empleado"));

        txtFecNac.setBackground(new java.awt.Color(255, 255, 255));
        txtFecNac.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtFecNac.setForeground(new java.awt.Color(0, 0, 0));
        txtFecNac.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Nacimiento"));

        txtFecIngreso.setBackground(new java.awt.Color(255, 255, 255));
        txtFecIngreso.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtFecIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtFecIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Incorporacion"));

        txtSalario.setBackground(new java.awt.Color(255, 255, 255));
        txtSalario.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        txtSalario.setForeground(new java.awt.Color(0, 0, 0));
        txtSalario.setBorder(javax.swing.BorderFactory.createTitledBorder("Salario Empleado"));
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });

        txtComision.setBackground(new java.awt.Color(255, 255, 255));
        txtComision.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtComision.setForeground(new java.awt.Color(0, 0, 0));
        txtComision.setBorder(javax.swing.BorderFactory.createTitledBorder("Comision Empleado"));

        txtCargoE.setBackground(new java.awt.Color(255, 255, 255));
        txtCargoE.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtCargoE.setForeground(new java.awt.Color(0, 0, 0));
        txtCargoE.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo Empleado"));
        txtCargoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoEActionPerformed(evt);
            }
        });

        txtJefeID.setBackground(new java.awt.Color(255, 255, 255));
        txtJefeID.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtJefeID.setForeground(new java.awt.Color(0, 0, 0));
        txtJefeID.setBorder(javax.swing.BorderFactory.createTitledBorder("JefeID"));

        txtcodDepto.setBackground(new java.awt.Color(255, 255, 255));
        txtcodDepto.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtcodDepto.setForeground(new java.awt.Color(0, 0, 0));
        txtcodDepto.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo Departamento"));
        txtcodDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodDeptoActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(102, 102, 102));
        btnAgregar.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-tarea.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setDefaultCapable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(102, 102, 102));
        btnActualizar.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar (4).png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar_1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setDefaultCapable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSexEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuariosLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtComision))
                        .addGap(18, 18, 18)
                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                .addComponent(txtCargoE, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJefeID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtcodDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNomEmp, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecNac)
                        .addComponent(txtSexEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecIngreso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDEmp)
                    .addComponent(txtID))
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlUsuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJefeID)
                            .addComponent(txtcodDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pnlDatos.setBackground(new java.awt.Color(102, 102, 102));
        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Usuarios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDatosMouseClicked(evt);
            }
        });

        tblPanel.setBackground(new java.awt.Color(255, 255, 255));
        tblPanel.setForeground(new java.awt.Color(0, 0, 0));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        tblPanel.setViewportView(tblUsuarios);

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomEmpActionPerformed

    private void txtIDEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDEmpActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String insertarSQL = "INSERT INTO empleados (nDIEmp, nomEmp, sexEmp, fecNac, fecIncorporacion, salEmp, comisionE, cargoE, jefeID, codDepto) values (?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement ps;
            ps = (PreparedStatement) cx.prepareStatement(insertarSQL);
            ps.setString(1, txtIDEmp.getText());
            ps.setString(2, txtNomEmp.getText());
            ps.setString(3, txtSexEmp.getText());
            ps.setString(4, txtFecNac.getText());
            ps.setString(5, txtFecIngreso.getText());
            ps.setString(6, txtSalario.getText());
            ps.setString(7, txtComision.getText());
            ps.setString(8, txtCargoE.getText());
            ps.setString(9, txtJefeID.getText());
            ps.setString(10, txtcodDepto.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Registro ingresado sastifactoriamente");
            btnActualizar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnAgregar.setEnabled(true);
            mostrarDatos("");
            limpiarcampos();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar agregar usuario");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String actualizarSQL = "UPDATE empleados SET nomEmp='" + txtNomEmp.getText()
                + "', sexEmp ='" + txtSexEmp.getText()
                + "', fecNac ='" + txtFecNac.getText()
                + "', fecIncorporacion ='" + txtFecIngreso.getText()
                + "', salEmp ='" + txtSalario.getText()
                + "', comisionE ='" + txtComision.getText()
                + "', cargoE ='" + txtCargoE.getText()
                + "', jefeID ='" + txtJefeID.getText()
                + "', codDepto ='" + txtcodDepto.getText()
                + "' WHERE id =" + txtID.getText();
        try {
            PreparedStatement ps;
            ps = (PreparedStatement) cx.prepareStatement(actualizarSQL);
            int indice = ps.executeUpdate();
            if (indice > 0) {
                JOptionPane.showMessageDialog(rootPane, "Datos actualizados correctamente.");
                btnActualizar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnAgregar.setEnabled(true);
                mostrarDatos("");
                limpiarCampos();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error al actualizar datos: " + ex);
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        mostrarDatos("");
        btnActualizar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAgregar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void pnlDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDatosMouseClicked
        btnActualizar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAgregar.setEnabled(true);
        mostrarDatos("");
        limpiarCampos();
    }//GEN-LAST:event_pnlDatosMouseClicked
    
    private void pnlUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlUsuariosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        mostrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void popEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminara el registro, quieres continuar?", "Eliminar Registro",
                JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                String Borrar = "DELETE FROM empleados WHERE id='" + txtID.getText() + "'";
                PreparedStatement ps;
                ps = (PreparedStatement) cx.prepareStatement(Borrar);
                int respuesta = ps.executeUpdate();
                if (respuesta > 0) {
                    JOptionPane.showMessageDialog(null, "Registro eliminado con exito!");
                    limpiarCampos();
                    mostrarDatos("");
                } else {
                    JOptionPane.showMessageDialog(null, "No ha seleccionado la fila a ser borrada.");
                    limpiarCampos();
                    mostrarDatos("");
                }
            } catch (SQLException e) {
                System.err.println("Error al eliminar...." + e);
                JOptionPane.showMessageDialog(null, "Error al eliminar!");
            }

        } else {
            limpiarCampos();
            mostrarDatos("");
            btnActualizar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnAgregar.setEnabled(true);
        }
    }//GEN-LAST:event_popEliminarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        btnAgregar.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnCancelar.setEnabled(true);
        int fila = this.tblUsuarios.getSelectedRow();
        txtID.setText(this.tblUsuarios.getValueAt(fila, 0).toString());
        txtIDEmp.setText(this.tblUsuarios.getValueAt(fila, 1).toString());
        txtNomEmp.setText(this.tblUsuarios.getValueAt(fila, 2).toString());
        txtSexEmp.setText(this.tblUsuarios.getValueAt(fila, 3).toString());
        txtFecNac.setText(this.tblUsuarios.getValueAt(fila, 4).toString());
        txtFecIngreso.setText(this.tblUsuarios.getValueAt(fila, 5).toString());
        txtSalario.setText(this.tblUsuarios.getValueAt(fila, 6).toString());
        txtComision.setText(this.tblUsuarios.getValueAt(fila, 7).toString());
        txtCargoE.setText(this.tblUsuarios.getValueAt(fila, 8).toString());
        txtJefeID.setText(this.tblUsuarios.getValueAt(fila, 9).toString());
        txtcodDepto.setText(this.tblUsuarios.getValueAt(fila, 10).toString());
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtCargoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoEActionPerformed

    private void txtcodDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodDeptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmpleadosCRUD().setVisible(true);
        });
    }
    
    private void mostrarDatos(String valorBuscar) {
        String consultaSQL = "SELECT * FROM empleados WHERE CONCAT(nDIEmp,'',nomEmp) LIKE '%" + valorBuscar + "%'";
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("nDIEmp");
        modelo.addColumn("nomEmp");
        modelo.addColumn("sexEmp");
        modelo.addColumn("fecNac");
        modelo.addColumn("fecIncorporacion");
        modelo.addColumn("salEmp");
        modelo.addColumn("comisionE");
        modelo.addColumn("cargoE");
        modelo.addColumn("jefeID");
        modelo.addColumn("codDepto");
        tblUsuarios.setModel(modelo);
        String data[] = new String[11];
        Statement st;
        try {
            st = (Statement) cx.createStatement();
            ResultSet rs = st.executeQuery(consultaSQL);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);
                data[6] = rs.getString(7);
                data[7] = rs.getString(8);
                data[8] = rs.getString(9);
                data[9] = rs.getString(10);
                data[10] = rs.getString(11);
                modelo.addRow(data);
            }
            tblUsuarios.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la consulta SQL: " + ex);
        }
    }
    
    private void limpiarCampos() {
        txtIDEmp.setText("");
        txtNomEmp.setText("");
        txtSexEmp.setText("");
        txtFecNac.setText("");
        txtFecIngreso.setText("");
        txtSalario.setText("");
        txtComision.setText("");
        txtCargoE.setText("");
        txtJefeID.setText("");
        txtcodDepto.setText("");
        txtNomEmp.requestFocus();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JMenuItem popEliminar;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JScrollPane tblPanel;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCargoE;
    private javax.swing.JTextField txtComision;
    private javax.swing.JTextField txtFecIngreso;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDEmp;
    private javax.swing.JTextField txtJefeID;
    private javax.swing.JTextField txtNomEmp;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSexEmp;
    private javax.swing.JTextField txtcodDepto;
    // End of variables declaration//GEN-END:variables

    private void limpiarcampos() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
}

